SmtCore.cpp compilation issue - "copy from type const Tightening"
Running "cmake --build ." causes the compiler to throw an error stating
that we should be using a reference instead of copying the "Tightening"
object. This PR just fixes the compilation error.

Marabou/src/engine/SmtCore.cpp:339:22: error: loop
      variable 'bound' of type 'const Tightening' creates a copy from type 'const Tightening'
      [-Werror,-Wrange-loop-analysis]
    for ( const auto bound : split.getBoundTightenings() )
                     ^
Marabou/src/engine/SmtCore.cpp:339:11: note: use
      reference type 'const Tightening &' to prevent copying
    for ( const auto bound : split.getBoundTightenings() )
          ^~~~~~~~~~~~~~~~~~