Fix a compilation issue on Mac.
I was getting the following error on build:

/Marabou/src/engine/ReluConstraint.cpp:913:14: error: call to 'abs' is ambiguous
    _score = std::abs( computePolarity() );
             ^~~~~~~~
Generally this probably happens because computePolarity() returns double, and abs accepts int or long int.

In cmath there is abs that accepts double, hence this fixed the issue.